version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - db
    ports:
      - 5000:5000

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_DB=daily_users

volumes:
  postgres_data: